name: vokki
description: "App for building vocabulary with fun"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  flutter_layout_grid: ^2.0.5
  rxdart: ^0.27.7
  go_router: ^13.2.2
  riverpod_annotation: ^2.3.5
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
