name: vokki
description: "App for building personal vocabulary with fun"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_layout_grid: ^2.0.7
  rxdart: ^0.28.0
  go_router: ^14.2.3
  riverpod_annotation: ^2.3.5
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  equatable: ^2.0.5
  cloud_firestore: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  algolia: ^1.1.2
  envied: ^0.5.4
  envied_generator: ^0.5.4
  google_mlkit_text_recognition: ^0.13.0
  camera: ^0.11.0
  permission_handler: ^11.3.1
  flutter_gemini: ^2.0.5
  #commented out since it's incompatible with flutter_secure_storage
  #speech_to_text: ^6.6.2
  flutter_tts: ^4.0.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  vokki_openapi:
    git:
      url: git@github.com:noskova/vokki-openapi.git
      ref: main
      path: dart
  dio: ^5.6.0
  built_value: ">=8.4.0 <9.0.0"
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.2

dependency_overrides:
  meta: ^1.14.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
