name: vokki
description: "App for building personal vocabulary with fun"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_layout_grid: ^2.0.6
  rxdart: ^0.27.7
  go_router: ^14.0.1
  riverpod_annotation: ^2.3.5
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  equatable: ^2.0.5
  cloud_firestore: ^4.17.2
  flutter_staggered_grid_view: ^0.7.0
  algolia: ^1.1.2
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1
  google_mlkit_text_recognition: ^0.13.0
  camera: ^0.11.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
