// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'app_user.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.

typedef UserID = String;

@freezed
class AppUser with _$AppUser {
  const factory AppUser({
    required UserID uid,
    required String? email,
    required bool emailVerified,
  }) = _AppUser;
}
